# Site settings
title: "Jacob R. Romeo"
email: "jromeo@hawaii.edu"
description: "Personal website and portfolio"
baseurl: "" # Leave empty for the root directory
url: "https://ravingross.github.io" # Your GitHub Pages URL or custom domain

# Author information
author:
  name: "Jacob Romeo"
  email: "jromeo@hawaii.edu"

# Build settings
markdown: kramdown
theme: minimal-mistakes-jekyll # A simple and elegant theme

# Social links
social:
  orcid: "https://orcid.org/0009-0000-3896-230X"
  github: "https://github.com/RavingRoss"
  linkedin: "https://www.linkedin.com/in/jacob-romeo-ce-301124191/"
  email: "jromeo@hawaii.edu"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Other settings
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"