# Site settings
title: "Jacob R. Romeo"
email: "jromeo@hawaii.edu"
description: "Personal website and portfolio"
baseurl: "" # Leave empty for the root directory
url: "https://ravingross.github.io" # Your GitHub Pages URL or custom domain

# Author information
author:
  name: "Jacob Romeo"
  email: "jromeo@hawaii.edu"

# Theme and Appearance
theme: minimal-mistakes-jekyll # A simple and elegant theme
minimal_mistakes_skin: "air" # "air", "plum", or "dark" for diff styles

# Social links
social:
  orcid: "https://orcid.org/0009-0000-3896-230X"
  github: "https://github.com/RavingRoss"
  linkedin: "https://www.linkedin.com/in/jacob-romeo-ce-301124191/"
  email: "jromeo@hawaii.edu"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache # Required by MM

# Pagination settings
paginate: 5
paginate_path: "/page:num/"

# Navigation (optional, for top menu)
# Create _data/navigation.yml to customize
# navigation:
#   - title: "About"
#     url: /about/
#   - title: "Research"
#     url: /research/
#   - title: "CV"
#     url: /cv/
#   - title: "Contact"
#     url: /contact/

# Other settings
markdown: kramdown
exclude:
  - "README.md"
  - "Gemfile"
  - "Gemfile.lock"
